tabs:
    content:
        label: Content
        icon: text
        columns:
            - width: 2/3
              sections:
                  komments:
                      extends: sections/komments
                  mastodon:
                      type: fields
                      fields:
                          extends: fields/mastodonUrl
            - width: 1/3
              sections:
                  customFields:
                      type: fields
                      fields:
                          kommentsPending:
                              type: kommentsPending
                              label: Pending Komments
    testtab:
        label: Stats
        icon: text
        sections:
            stats:
                type: stats
                # Available size options: small, medium, large, huge. Default is large
                size: huge
                reports:
                    - label: Pending Comments
                      value: '{{ site.numberOfPendingComments }}'
                      info: 'Possible spam: {{ site.numberOfSpamComments }}'
                      link: https://getkirby.com/shop
                      theme: negative
